### PR TITLE
fix: pins should not be inherited

### LINKED ISSUE #841: [BUG] Pins are not supposed to be inherited anymore, but inherited pins show up when pinning content further down
This is an issue related to legacy behaviour that has not been completely removed.

## Expected behaviour

When pinning an item in a folder, it will be shown inside the side panel for the current page/folder only. 
The pins should not be inherited anymore.

## Reproducing the issue

1. Create a parent folder "A".
2. Create 2 text elements, one says "I am pinned from A" the other "I am regular"
3. create 2 child folders "B1" and "B2".
4. Inside B1, create a text element "text in B1"
5. Inside B2, create 2 text elements "I am pinned from B2" and "I am regular from B2"

Current behaviour:
- "I am pinned from A" is showing in the pinned elements when viewing A
- There are no pinned elements in B1
- "I am pinned from A" is showing in the pinned elements when viewing B2 -> **this should not be shown in B2**
- "I am pinned from B2" is showing in the pinned elements when viewing B2

Expected behaviour: Only pinned children from the current folder should be shown in the pinned tab. Pinned elements from parents should not be shown in children elements.

### PR DESCRIPTION
**Pull request by spaenleh**
fix #841

### CODE REVIEW

File: src/modules/navigation/tree/LoadingTree.tsx [hunk 1]
```diff
@@ -2,11 +2,13 @@ import { Skeleton, Stack, Typography } from '@mui/material';
 
 const LoadingTree = (): JSX.Element => (
   <Stack p={1}>
-    {Array.from(Array(5)).map(() => (
-      <Typography>
-        <Skeleton variant="text" />
-      </Typography>
-    ))}
+    {Array.from(['elem 1', 'elem 2', 'elem 3', 'elem 4', 'elem 5']).map(
```
Comment (ReidyT) [inline src/modules/navigation/tree/LoadingTree.tsx:5]: I think you can remove the `Array.from`.

```suggestion
    {['elem 1', 'elem 2', 'elem 3', 'elem 4', 'elem 5'].map(
```

File: src/modules/rightPanel/SideContent.tsx [hunk 2]
```diff
@@ -154,22 +140,23 @@ const SideContent = ({ content, item }: Props): JSX.Element | null => {
...
-      </SideDrawer>
-    );
+    if (pinnedItems?.length) {
+      return (
+        <SideDrawer
+          title={t(PLAYER.PINNED_ITEMS)}
+          onClose={togglePinned}
+          open={isPinnedOpen}
+        >
+          {/* show parents pinned items */}
```
Comment (ReidyT) [inline src/modules/rightPanel/SideContent.tsx:150]: It is still parents pinned items or children pinned items?

**Review by ReidyT — APPROVED** [review]
Nice changes, LGTM
