### PR TITLE
fix: set pinned side content isopen default value to false

### LINKED ISSUE #470: [responsive] Pinned Items drawer opens by default on mobile
When on mobile, the pinned items drawer is open.
It should be closed on mobile

### PR DESCRIPTION
**Pull request by LinaYahya**
close #470

### CODE REVIEW

File: src/contexts/LayoutContext.tsx [hunk 1]
```diff
@@ -19,7 +21,9 @@ type Props = {
 };
 
 export const LayoutContextProvider = ({ children }: Props): JSX.Element => {
-  const [isPinnedMenuOpen, setIsPinnedMenuOpen] = useState<boolean>(true);
+  const { isMobile } = useMobileView();
+
+  const [isPinnedMenuOpen, setIsPinnedMenuOpen] = useState<boolean>(!isMobile);
```
Comment (spaenleh) [inline src/contexts/LayoutContext.tsx:26]: Not sure if it was the intent, but this value will only set the initial value of the state. If there is a change afterwards they will not be synched.

**Review by spaenleh — APPROVED** [review]
Looks good 📌  just let me know if your intent was to only set the initial, or if you wanted to maybe have it update during the lifetime of the component.

File: src/contexts/LayoutContext.tsx (hunk 1 above)
Comment (LinaYahya) [reply src/contexts/LayoutContext.tsx:26]: @spaenleh 
Do u think normal user going to change screen size, It might be fixed using useeffect to synd the value 👍🏼

Comment (spaenleh) [reply src/contexts/LayoutContext.tsx:26]: Not sure it is needed, but I just wanted to make sure that it was omitted for a reason.
